<a href="https://colab.research.google.com/github/maheshs1ngh/Data-science-projects/blob/main/NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [ ]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
import numpy as np
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed

random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
# Your code here
#average value of the first 5 rows of the third and fourth columns?
#print(random_integers)
array=random_integers[0:5, 2:4]
print(array)
np.average(array)

[[202553 140037]
 [261540 481981]
 [110795 394863]
 [408830 485118]
 [265455 109413]]


286058.5

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points
import numpy as np
import random

def euclidean_distance(x, y):
  return np.sqrt(np.sum((x - y)**2))

def manhattan_distance(x, y):
  return np.sum(np.abs(x - y))

# array of 10 points
points = np.random.randint(5, 20, size=(10, 2))
print("array of points:\n", points)

array of points:
 [[11 16]
 [10  9]
 [19 17]
 [ 8 15]
 [19 10]
 [ 8 11]
 [ 8 19]
 [ 7 15]
 [ 8  6]
 [ 7  7]]


In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
euclidean_distances = np.zeros((10, 10))
for i in range(10):
  for j in range(10):
    euclidean_distances[i, j] = euclidean_distance(points[i], points[j])

print(euclidean_distances)



[[ 0.          4.12310563  9.05538514 11.40175425  9.43398113 10.81665383
  15.          2.23606798  5.65685425 11.66190379]
 [ 4.12310563  0.         10.44030651  7.28010989  5.65685425  8.60232527
  12.80624847  6.          3.          9.21954446]
 [ 9.05538514 10.44030651  0.         15.62049935 15.65247584  8.54400375
  11.         10.44030651 13.34166406  9.48683298]
 [11.40175425  7.28010989 15.62049935  0.          3.60555128  9.21954446
  12.04159458 13.15294644  7.07106781  9.05538514]
 [ 9.43398113  5.65685425 15.65247584  3.60555128  0.         11.04536102
  14.56021978 10.77032961  4.12310563 11.18033989]
 [10.81665383  8.60232527  8.54400375  9.21954446 11.04536102  0.
   4.24264069 13.03840481 11.18033989  1.        ]
 [15.         12.80624847 11.         12.04159458 14.56021978  4.24264069
   0.         17.20465053 15.26433752  3.60555128]
 [ 2.23606798  6.         10.44030651 13.15294644 10.77032961 13.03840481
  17.20465053  0.          6.70820393 13.89244399]
 [ 5.656

In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
manhattan_distances = np.zeros((10, 10))
for i in range(10):
  for j in range(10):
     manhattan_distances[i, j] = manhattan_distance(points[i][np.newaxis, :], points[j][np.newaxis, :])
print(manhattan_distances)



[[ 0.  5. 10. 14. 13. 15. 21.  3.  8. 16.]
 [ 5.  0. 13.  9.  8. 12. 18.  6.  3. 13.]
 [10. 13.  0. 22. 21. 11. 11. 13. 16. 12.]
 [14.  9. 22.  0.  5. 11. 13. 15.  8. 10.]
 [13.  8. 21.  5.  0. 12. 18. 14.  5. 13.]
 [15. 12. 11. 11. 12.  0.  6. 18. 15.  1.]
 [21. 18. 11. 13. 18.  6.  0. 24. 21.  5.]
 [ 3.  6. 13. 15. 14. 18. 24.  0.  9. 19.]
 [ 8.  3. 16.  8.  5. 15. 21.  9.  0. 16.]
 [16. 13. 12. 10. 13.  1.  5. 19. 16.  0.]]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here
import numpy as np

def euclidean_distance(x, y):
  return np.sqrt(np.sum((x - y)**2))

points = np.random.randint(5, 20, size=(10, 2))
print( points)
closest_pair = (0, 1)
min_distance = euclidean_distance(points[0], points[1])


    

print(closest_pair)

[[16 19]
 [10 18]
 [13 14]
 [17  5]
 [19  5]
 [10  6]
 [ 8 19]
 [13 15]
 [ 8  9]
 [10 16]]
(0, 1)


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..
import numpy as np
rand=np.random.randint(1000,size= (10,10))
print(rand)

block=[]

for i in range(rand.shape[0]-2):
  for a in range(rand.shape[0]-2):
    block.append(rand[i:i+3,a:a+3])

print(len(block))
print(block)



[[316 729 522 806 170 483 548 157 324 922]
 [853 672 135 814 898  89 357 664 991 336]
 [755 322 524 650 126 529 172 385 122 633]
 [984 532 981 135 791 460 791 386 736 449]
 [660 551  41 235 525 991 431 275 336 601]
 [713 498 125 933 293 795  66 824 142 822]
 [913 988 988 528  35 699 228 410 469 733]
 [410 964 950 108 238 659 546 670 437 525]
 [502  41  45 187 557 436 837 755 937 247]
 [575 791 720 981 629  58 960 890  49 472]]
64
[array([[316, 729, 522],
       [853, 672, 135],
       [755, 322, 524]]), array([[729, 522, 806],
       [672, 135, 814],
       [322, 524, 650]]), array([[522, 806, 170],
       [135, 814, 898],
       [524, 650, 126]]), array([[806, 170, 483],
       [814, 898,  89],
       [650, 126, 529]]), array([[170, 483, 548],
       [898,  89, 357],
       [126, 529, 172]]), array([[483, 548, 157],
       [ 89, 357, 664],
       [529, 172, 385]]), array([[548, 157, 324],
       [357, 664, 991],
       [172, 385, 122]]), array([[157, 324, 922],
       [664, 991, 336],

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below

import numpy as np

def nearest_value(arr, value):
    idx = (np.abs(arr - value)).argmin()
    return arr[idx]

import numpy as np

arr = np.random.randint(10, 500, 15)
value = np.random.randint(10, 500)
nearest = nearest_value(arr, value)

print("Array:", arr)
print("Value:", value)
print("Nearest value:", nearest)

Array: [212 482 210 320 379 456  42 446  63  78 228 373 405 483 352]
Value: 55
Nearest value: 63
